{% set name = "cellrank" %}
{% set version = "2.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cellrank-{{ version }}.tar.gz
  sha256: 88a9f8044d80bc7c82b5cfc68ae6a2a2fd954b344c10f7e3ddf9b3a3262a6f50

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - anndata >=0.9
    - docrep >=0.3.0
    - joblib >=0.13.1
    - matplotlib-base >=3.5.0
    - networkx >=2.2
    - numba >=0.51.0,!=0.57.0
    - numpy >=1.22.0
    - pandas >=1.5.0
    - pygam >=0.8.0
    - pygpcca >=1.0.4
    - scanpy >=1.7.2
    - scikit-learn >=0.24.0
    - scipy >=1.2.0
    - scvelo >=0.2.5
    - seaborn >=0.10.0
    - wrapt >=1.12.1

test:
  imports:
    - cellrank
  commands:
    - pip check
  requires:
    - pip

about:
  summary: 'CellRank: dynamics from multi-view single-cell data'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mfansler
