{% set name = "pcst-fast" %}
{% set version = "1.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pcst_fast-{{ version }}.tar.gz
  sha256: 3b5694110ce2e004471f383267d5e4ab7fe1ba9828954e8c42560ac1e42b25e6

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - python
    - pybind11 >=2.1.0
    - setuptools-scm
    - pip
  run:
    - python
    - pybind11 >=2.1.0

test:
  imports:
    - pcst_fast
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fraenkel-lab/pcst_fast
  summary: A fast implementation of the Goemans-Williamson scheme for the prize-collecting Steiner tree / forest problem.
  license: MIT AND BSD-3-Clause AND Apache-2.0
  license_file:
    - LICENSE.txt
    - external/pybind11/LICENSE
    - external/googletest/googletest/LICENSE
    - external/googletest/googlemock/LICENSE
    - external/googletest/googlemock/scripts/generator/LICENSE

extra:
  recipe-maintainers:
    - mfansler
