{% set version = '1.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-changepoints
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/changepoints_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/changepoints/changepoints_{{ version }}.tar.gz
  sha256: 73b7e389d8d5590d91ecb369f57b80f605b3c9f231da04be54a650b9b9c593f1

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-rcpp
    - r-rcpparmadillo
    - r-data.tree
    - r-gglasso
    - r-glmnet
    - r-ks
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-mass
    - r-rcpp
    - r-rcpparmadillo
    - r-data.tree
    - r-gglasso
    - r-glmnet
    - r-ks

test:
  commands:
    - $R -e "library('changepoints')"           # [not win]
    - "\"%R%\" -e \"library('changepoints')\""  # [win]

about:
  home: https://github.com/HaotianXu/changepoints
  license: GPL-3
  summary: 'Performs a series of offline and/or online change-point detection algorithms for
    1) univariate mean: <doi:10.1214/20-EJS1710>, <arXiv:2006.03283>; 2) univariate
    polynomials: <doi:10.1214/21-EJS1963>; 3) univariate and multivariate nonparametric
    settings: <doi:10.1214/21-EJS1809>, <doi:10.1109/TIT.2021.3130330>; 4) high-dimensional
    covariances: <doi:10.3150/20-BEJ1249>; 5) high-dimensional networks with and without
    missing values: <doi:10.1214/20-AOS1953>, <arXiv:2101.05477>, <arXiv:2110.06450>;
    6) high-dimensional linear regression models: <arXiv:2010.10410>, <arXiv:2207.12453>;
    7) high-dimensional vector autoregressive models: <arXiv:1909.06359>; 8) high-dimensional
    self exciting point processes: <arXiv:2006.03572>; 9) dependent dynamic nonparametric
    random dot product graphs: <arXiv:1911.07494>; 10) univariate mean against adversarial
    attacks: <arXiv:2105.10417>.'
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: changepoints
# Type: Package
# Title: A Collection of Change-Point Detection Methods
# Version: 1.1.0
# Date: 2022-08-25
# Authors@R: c( person("Haotian", "Xu", email="haotian.xu@uclouvain.be", role=c("aut","cre")), person("Oscar", "Padilla", email="oscar.madrid@stat.ucla.edu", role="aut"), person("Daren", "Wang", email="dwang24@nd.edu", role="aut"), person("Mengchu", "Li", email="Mengchu.Li@warwick.ac.uk", role="aut"), person("Qin", "Wen", role="ctb") )
# Maintainer: Haotian Xu <haotian.xu@uclouvain.be>
# Description: Performs a series of offline and/or online change-point detection algorithms for 1) univariate mean: <doi:10.1214/20-EJS1710>, <arXiv:2006.03283>; 2) univariate polynomials: <doi:10.1214/21-EJS1963>; 3) univariate and multivariate nonparametric settings: <doi:10.1214/21-EJS1809>, <doi:10.1109/TIT.2021.3130330>; 4) high-dimensional covariances: <doi:10.3150/20-BEJ1249>; 5) high-dimensional networks with and without missing values: <doi:10.1214/20-AOS1953>, <arXiv:2101.05477>, <arXiv:2110.06450>; 6) high-dimensional linear regression models: <arXiv:2010.10410>, <arXiv:2207.12453>; 7) high-dimensional vector autoregressive models: <arXiv:1909.06359>; 8) high-dimensional self exciting point processes: <arXiv:2006.03572>; 9) dependent dynamic nonparametric random dot product graphs: <arXiv:1911.07494>; 10) univariate mean against adversarial attacks: <arXiv:2105.10417>.
# Depends: R (>= 3.5.0)
# Imports: stats, gglasso, glmnet, ks, MASS, data.tree, Rcpp
# Suggests: knitr, abind, DiagrammeR, rmarkdown
# LinkingTo: Rcpp, RcppArmadillo
# License: GPL (>= 3)
# RoxygenNote: 7.2.1
# Encoding: UTF-8
# URL: https://github.com/HaotianXu/changepoints
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2022-08-25 15:59:18 UTC; haotianxu
# Author: Haotian Xu [aut, cre], Oscar Padilla [aut], Daren Wang [aut], Mengchu Li [aut], Qin Wen [ctb]
# Repository: CRAN
# Date/Publication: 2022-09-04 14:30:08 UTC
